language: ruby
dist: trusty
bundler_args: --without debugging documentation
branches:
  only:
    - master
    - /.+-stable$/
addons:
 code_climate:
   repo_token: 186c49521e629c51591c86f057f49fe388ce87603e04b5486f0c92f26f2a455f
rvm:
  - 2.0.0-p647
  - 2.3.4
  - 2.4.1
  - 2.6.2
  - 2.7.0
env:
  - LANG="en_US.UTF-8"
script: bundle exec rake spec
git:
  submodules: false
before_install:
  - gem install bundler -v "~> 1.17"
  - |
      git submodule update --init
      (
        cd spec/fixtures/spec-repos/test_repo
        git init
        git remote add origin https://bitbucket.com/test/test_repo.git
      )
