language: ruby
bundler_args: --without debugging documentation
branches:
  only:
    - master
    - /.+-stable$/
addons:
 code_climate:
   repo_token: 186c49521e629c51591c86f057f49fe388ce87603e04b5486f0c92f26f2a455f
rvm:
  # Latest stable Ruby
  - 2.3.0
  # OS X 10.9.5-10.10.0 (2.0.0-p481)
  - 2.0.0-p481
  # OS X 10.9.3-10.9.4
  - 2.0.0-p451
  # OS X 10.9.0-10.9.2
  - 2.0.0-p247
env:
  - LANG="en_US.UTF-8"
script: bundle exec rake spec
git:
  submodules: false
before_install:
  - |
      master_sha="$(ruby -e "puts '`git submodule status spec/fixtures/spec-repos/master`'.strip.sub(/^-/, '').split(/\s/, 2).first")"
      curl -ssL "https://github.com/CocoaPods/Specs/archive/$master_sha.tar.gz" | tar xz -C spec/fixtures/spec-repos
      git rm spec/fixtures/spec-repos/master
      mv "spec/fixtures/spec-repos/Specs-$master_sha" spec/fixtures/spec-repos/master
      (
        cd spec/fixtures/spec-repos/master
        git init
        git remote add origin https://github.com/CocoaPods/Specs.git
      )
      git submodule update --init
